<template>
    <div>
        <table>
            <thead>
                <tr>
                    <th>Food Item</th>
                    <th>Serve Amount (g)</th>
                    <th>Total Carbs</th>
                    <th>Total Fat</th>
                    <th>Total Protein</th>
                    <th>Total Calories</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="(entry, index) in entries" :key="index">
                    <td>
                        <input type="text"
                               v-model="entry.name"
                               @input="autocomplete(index)"
                               :list="'food-list-' + index">
                        <datalist :id="'food-list-' + index">
                            <option v-for="food in filteredFoods(entry.name)" :value="food.name" :key="food.name"></option>
                        </datalist>
                    </td>
                    <td><input type="number" v-model.number="entry.amount" @input="calculateNutrients(index)"></td>
                    <td>{{ formatNumber(entry.carbs) }}</td>
                    <td>{{ formatNumber(entry.fat) }}</td>
                    <td>{{ formatNumber(entry.protein) }}</td>
                    <td>{{ entry.calories.toFixed(2) }}</td>
                    <td><button @click="removeEntry(index)">Remove</button></td>
                </tr>
            </tbody>
        </table>
        <button @click="addEntry">Add Food Item</button>
        <button @click="submitFoodLog">Submit Food Log</button>
    </div>
</template>

<script>
    import axios from 'axios';
    import { FoodItemDto } from '@/models/FoodItemDto';

    export default {
        props: {
            post: Array,
            entries: Array
        },
        methods: {
            addEntry() {
                this.entries.push({ name: '', amount: 0, calories: 0, carbs: 0, fat: 0, protein: 0 });
            },
            removeEntry(index) {
                this.entries.splice(index, 1);
            },
            calculateNutrients(index) {
                const entry = this.entries[index];
                const foodItem = this.post.find(food => food.name === entry.name);
                if (foodItem) {
                    entry.calories = (foodItem.calories / 100) * entry.amount;
                    entry.carbs = (foodItem.carbs / 100) * entry.amount;
                    entry.fat = (foodItem.fat / 100) * entry.amount;
                    entry.protein = (foodItem.protein / 100) * entry.amount;
                }
            },
            autocomplete(index) {
                this.calculateNutrients(index);
            },
            filteredFoods(searchTerm) {
                if (!searchTerm) return [];
                const lowerCaseTerm = searchTerm.toLowerCase();
                return this.post.filter(food => food.name.toLowerCase().includes(lowerCaseTerm));
            },
            formatNumber(value) {
                return Number(value).toFixed(2);
            },
            submitFoodLog() {
                const foodLogDto = {
                    Id: null, // Assuming it's generated by the backend
                    DateTime: new Date(),
                    TotalCalories: this.entries.reduce((total, item) => total + item.calories, 0),
                    TotalCarbs: this.entries.reduce((total, item) => total + item.carbs, 0),
                    TotalProtein: this.entries.reduce((total, item) => total + item.protein, 0),
                    TotalFat: this.entries.reduce((total, item) => total + item.fat, 0),
                    FoodItems: this.entries.map(item => new FoodItemDto(item.name, item.calories, item.carbs, item.protein, item.fat)),
                    CreateTime: new Date(), // Optionally managed by the server
                    UpdateTime: new Date(), // Optionally managed by the server
                    UserId: this.userId,
                };

                axios.post('/foodlog/createfoodlog', foodLogDto )
                    .then(response => {
                        console.log('Food log created successfully:', response.data);
                        alert('Food log submitted successfully!');
                    })
                    .catch(error => {
                        console.error('Error creating food log:', error);
                        alert('Failed to submit food log!');
                    });
            }
        }
    }
</script>
