using AutoMapper;
using NT.Application.Contracts.Entities;

namespace NutritionTracker.Api.Profilers;

public class FoodItemDtoProfiler : Profile
{
    public FoodItemDtoProfiler()
    {
        //CreateMap<FoodItemEntity, FoodItemDto>().ReverseMap();

        CreateMap<FoodItemDto, FoodItemEntity>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // Assuming Id is managed differently or generated by the database
            .ForMember(dest => dest.FoodLogId, opt => opt.MapFrom(src => src.FoodLogId))
            .ForMember(dest => dest.FoodNutritionId, opt => opt.MapFrom(src => src.FoodNutritionId))
            .ForMember(dest => dest.Unit, opt => opt.MapFrom(src => src.Unit))
            ;
    }
}
